/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Pattern {
  x: Array<number>
  y: Array<number>
  e?: Array<number>
}

export declare function read(path: string): Pattern

export declare function readBytes(data: Buffer, filename: string): Pattern
